const characterActionTypes = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_CHARACTERS_PENDING: 'GET_CHARACTERS_PENDING',
  GET_CHARACTERS_ERROR: 'GET_CHARACTERS_ERROR',
  GET_SELECTED_CHARACTER: 'GET_SELECTED_CHARACTER',
};

export default characterActionTypes;
